### ISSUE TITLE
Clean.py is not working properly.

### ISSUE THREAD

**Issue by lebshah** [gnijuohz/geeksforgeeks-as-books#1]
The code is failing at this point

cleaned_file = os.path.splitext(basename)[0] + "_cleaned.html"

and then the exception is thrown. BTW I am working on windows.

**Comment by gnijuohz** [comment]
Hi thanks for reporting this. It seems I somehow moved the definition of `basename` down in the file. I have corrected this.

**Comment by lebshah** [comment]
Thanks a lot man. I worked on your code non-stop for the last two days. I never worked with python, beautiful soap and what not, but I learned them to modify your code. 

Some of the changes that I have done are:
1. Added time stamp in HTML to sort later based on article published date. Now we have a criteria to sort all the articles.Also added time stamp in HTML files beside Source. 
2. Removed Facebook,Twitter handle and the irritating Assistance link.
3.Your code was not working on windows so have to adapt it. I am still unable to run EPUB file code so I am doing that part manually.

**Comment by lebshah** [comment]
# -*- coding: utf-8 -*-
"""
clean local html files
"""

import glob
import sys
import codecs
import os
import logging
import HTMLParser
from subprocess import call

import lxml.etree
import lxml.html as html
from bs4 import UnicodeDammit
import datetime, dateutil.parser

from boilerpipy import (Extractor, isvalidhtml)


def insert_content(doc, html_doc, insert_string, insert_type):
    to_insert = html_doc.find('.//'+insert_type)
    doc.append(to_insert)
    return doc

def clean(file_name, directory="."):

    content = codecs.open(file_name, "r", 'utf-8').read()

    head_pos = content.find('<head>')

    # insert the encoding of the file
    content = content[:head_pos+6] + '<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">' + content[head_pos+6:]
    article = Extractor(content, loglevel = logging.INFO).extracted()

    if article is None:
        print "Error processing html file"
        sys.exit(1)
    html_parser = html.HTMLParser(encoding="utf-8")
    html_doc = html.fromstring(content, parser=html_parser)
    head_doc = html_doc.find('head')
    source_url = head_doc.cssselect('meta[property="og:url"]')[0].get('content')
    articlepublished_time = head_doc.cssselect('meta[property="article:published_time"]')[0].get('content')

    articlepublished_time_filename=dateutil.parser.parse(articlepublished_time).strftime('%Y%m%d')
    articlepublished_time_bookname=dateutil.parser.parse(articlepublished_time).strftime('%B %d, %Y')

    cleaned_file = os.path.splitext(os.path.basename(file_name))[0] +"_"+articlepublished_time_filename+ "_cleaned.html"
    # don't clean files that already have been cleaned
    if os.path.isfile(cleaned_file):
        return


    title = html_doc.find('.//title').text_content()

    # if the title is unfortunately removed by boilerpipy, then add it back in
    if "h2" not in article:
        article = "<h1>" + title[:title.rfind('-')] + "</h1>" + article

    reconstructed_body = "<html><body>" + article.replace("<h2", "<h1").replace("</h2>", "</h1>") + "</body></html>"
    source_header_string = "<td><h3>Source</h3></td>"
    article_published_date_string_link = "<td>" + articlepublished_time_bookname +"</td>"
    source_link = "<td><p><a href='" + source_url +"' rel='tag'>" + source_url + "</a></p></td>"
    #article_published_date_string = "<h3>Article Published Date</h3>"
    referencepageend="<table style='table-layout:fixed' width='1000'><tr>"+source_header_string+article_published_date_string_link+"</tr><tr>"+source_link+"</tr></table>"


    # further remove useless stuff
    body_doc = html.fromstring(reconstructed_body).find('body')
    for bad in body_doc.xpath("//div[@class='comments-main']"):
        bad.getparent().remove(bad)
    for ad_by_google in body_doc.xpath("//ins[@class='adsbygoogle']"):
        ad_by_google.getparent().remove(ad_by_google)
    for ad_by_facebook in body_doc.xpath("//iframe"):
        ad_by_facebook.getparent().remove(ad_by_facebook)
    #print articlepublished_time_bookname
    for post_navigation_assistive in body_doc.xpath("//nav[./p/@class='assistive-text']"):
        post_navigation_assistive.getparent().remove(post_navigation_assistive)
    for bad_h3 in body_doc.xpath("//h3"):
        bad_h3.getparent().remove(bad_h3)
    for pre_tag in body_doc.xpath("//pre"):
        if 'class' in pre_tag.attrib:
            pre_tag.attrib.pop('class')
        if 'title' in pre_tag.attrib:
            pre_tag.attrib.pop('title')
    
    post_content_doc = body_doc.xpath("//div[@class='entry-content']")[0]
    #post_content_doc.append(lxml.etree.XML(article_published_date_string))
    #post_content_doc.append(lxml.etree.XML(article_published_date_string_link))
    #post_content_doc.append(lxml.etree.XML(source_header_string))
    post_content_doc.append(lxml.etree.XML(referencepageend))
    basename = os.path.basename(file_name)
    result = html.tostring(body_doc)
    # replace <code> with <code><pre> for styling later.
    result = result.replace('<pre>', '<pre> <code>').replace('</pre>', '</code> </pre>')
    with open(directory + cleaned_file, 'w') as cleaned_file_handle:
        cleaned_file_handle.write(result.encode('utf-8'))


def clean_html_files(directory = ""):
    for html_file in sorted(glob.glob(directory + '*.html'), key=os.path.getmtime):
        if 'clean' not in html_file:
            try:
                clean(html_file, directory)
            except:
                print "WARNING: failed to clean", html_file

if __name__ == "__main__":
    clean(sys.argv[1])
    #clean_html_files("")

**Comment by lebshah** [comment]
# -*- coding: utf-8 -*-
"""
clean local html files
"""

import glob
import sys
import codecs
import os
import logging
import HTMLParser
from subprocess import call

import lxml.etree
import lxml.html as html
from bs4 import UnicodeDammit
import datetime, dateutil.parser

from boilerpipy import (Extractor, isvalidhtml)


def insert_content(doc, html_doc, insert_string, insert_type):
    to_insert = html_doc.find('.//'+insert_type)
    doc.append(to_insert)
    return doc

def clean(file_name, directory="."):

    content = codecs.open(file_name, "r", 'utf-8').read()

    head_pos = content.find('<head>')

    # insert the encoding of the file
    content = content[:head_pos+6] + '<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">' + content[head_pos+6:]
    article = Extractor(content, loglevel = logging.INFO).extracted()

    if article is None:
        print "Error processing html file"
        sys.exit(1)
    html_parser = html.HTMLParser(encoding="utf-8")
    html_doc = html.fromstring(content, parser=html_parser)
    head_doc = html_doc.find('head')
    source_url = head_doc.cssselect('meta[property="og:url"]')[0].get('content')
    articlepublished_time = head_doc.cssselect('meta[property="article:published_time"]')[0].get('content')

    articlepublished_time_filename=dateutil.parser.parse(articlepublished_time).strftime('%Y%m%d')
    articlepublished_time_bookname=dateutil.parser.parse(articlepublished_time).strftime('%B %d, %Y')

    cleaned_file = os.path.splitext(os.path.basename(file_name))[0] +"_"+articlepublished_time_filename+ "_cleaned.html"
    # don't clean files that already have been cleaned
    if os.path.isfile(cleaned_file):
        return


    title = html_doc.find('.//title').text_content()

    # if the title is unfortunately removed by boilerpipy, then add it back in
    if "h2" not in article:
        article = "<h1>" + title[:title.rfind('-')] + "</h1>" + article

    reconstructed_body = "<html><body>" + article.replace("<h2", "<h1").replace("</h2>", "</h1>") + "</body></html>"
    source_header_string = "<td><h3>Source</h3></td>"
    article_published_date_string_link = "<td>" + articlepublished_time_bookname +"</td>"
    source_link = "<td><p><a href='" + source_url +"' rel='tag'>" + source_url + "</a></p></td>"
    #article_published_date_string = "<h3>Article Published Date</h3>"
    referencepageend="<table style='table-layout:fixed' width='1000'><tr>"+source_header_string+article_published_date_string_link+"</tr><tr>"+source_link+"</tr></table>"


    # further remove useless stuff
    body_doc = html.fromstring(reconstructed_body).find('body')
    for bad in body_doc.xpath("//div[@class='comments-main']"):
        bad.getparent().remove(bad)
    for ad_by_google in body_doc.xpath("//ins[@class='adsbygoogle']"):
        ad_by_google.getparent().remove(ad_by_google)
    for ad_by_facebook in body_doc.xpath("//iframe"):
        ad_by_facebook.getparent().remove(ad_by_facebook)
    #print articlepublished_time_bookname
    for post_navigation_assistive in body_doc.xpath("//nav[./p/@class='assistive-text']"):
        post_navigation_assistive.getparent().remove(post_navigation_assistive)
    for bad_h3 in body_doc.xpath("//h3"):
        bad_h3.getparent().remove(bad_h3)
    for pre_tag in body_doc.xpath("//pre"):
        if 'class' in pre_tag.attrib:
            pre_tag.attrib.pop('class')
        if 'title' in pre_tag.attrib:
            pre_tag.attrib.pop('title')
    
    post_content_doc = body_doc.xpath("//div[@class='entry-content']")[0]
    #post_content_doc.append(lxml.etree.XML(article_published_date_string))
    #post_content_doc.append(lxml.etree.XML(article_published_date_string_link))
    #post_content_doc.append(lxml.etree.XML(source_header_string))
    post_content_doc.append(lxml.etree.XML(referencepageend))
    basename = os.path.basename(file_name)
    result = html.tostring(body_doc)
    # replace <code> with <code><pre> for styling later.
    result = result.replace('<pre>', '<pre> <code>').replace('</pre>', '</code> </pre>')
    with open(directory + cleaned_file, 'w') as cleaned_file_handle:
        cleaned_file_handle.write(result.encode('utf-8'))


def clean_html_files(directory = ""):
    for html_file in sorted(glob.glob(directory + '*.html'), key=os.path.getmtime):
        if 'clean' not in html_file:
            try:
                clean(html_file, directory)
            except:
                print "WARNING: failed to clean", html_file

if __name__ == "__main__":
    clean(sys.argv[1])
    #clean_html_files("")

**Comment by lebshah** [comment]
import re
import os
import sys
import glob
from subprocess import call
import fileinput
from clean import clean_html_files
from generate_covers import generate_cover

def generate(book):
    """
    generate books in epub and
    """
    if book[-1] != "/":
        book = book + "/"
    md_file = book + book[:-1]  + ".md"
    html_file = book + book[:-1]  + ".html"
    epub_file = book + book[:-1]  + ".epub"
    cover_image = "covers/" + book[:-1] + ".png"
    print "cleaning html files,", "this might take a while..."
    clean_html_files(book)
    #print "Files are susccesfully cleaned."
    #cleaned_html = sorted(glob.glob(book + "*_cleaned.html"))
    #print "Files are sorted timestamp wise."
    #print cleaned_html
    cleaned_html = sorted(glob.glob(book + "*_cleaned.html"), key=lambda x: int(x.split('_')[1]))
    #print cleaned_html 
    with open(html_file, 'w') as fout:
        #cleaned_html = sorted(glob.glob(book + "*_cleaned.html"))
        for line in fileinput.input(cleaned_html):
            fout.write(line)
            # don't want to copy the output into the output again.
            #if line == fout:
            #   continue
                          
    #print "generating", html_file, "..."
    #call("type " + "COPYRIGHT" + " ".join(cleaned_html) + " > " + html_file, shell=True)
    #try:
    #    generate_cover(book[:-1])
    #except:
    #    print "can't generate cover for", book[:-1]
    #call('pandoc --latex-engine=xelatex ' + html_file + ' -o ' + html_file.replace('html', 'docx'), shell=True)
    #print "generating", epub_file, "this might take a while..."
    #print book+"'metadata.xml'"
    #call(['pandoc', '-o', epub_file, cleaned_html, '--epub-metadata='+book+'metadata.xml', "--toc", "--toc-depth=2", "--epub-stylesheet=../styles/buttondown.css", "-f", "html-native_divs"])
    #print "generating", book + book[:-1] + ".mobi", "..."
   # call(['kindlegen', epub_file])

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print "this program takes a book name"
        sys.exit()
    book = sys.argv[1]
    generate(book)

**Comment by lebshah** [comment]
pandoc -o c-arrays/c-arrays.epub c-arrays/c-arrays.html --epub-metadata=c-arrays/metadata.xml --toc --toc-depth=2 --epub-stylesheet=styles/buttondown.css -f html-native_divs

scrapy crawl geeksforgeeks -a category=category -a name=c-arrays

python generate_book.py linked-list[This is the folder name. Should add 1.0 if required :P]

**Comment by lebshah** [comment]
Thanks a lot man. Awesome work.

**Comment by lebshah** [comment]
Let me know a good Python IDE. I worked with Sublime Text 3 with no support for debugging. So you might see a lot of commented out Print statements in the code. Please clean it accordingly.

**Comment by lebshah** [comment]
Main change in generate_book is 

   cleaned_html = sorted(glob.glob(book + "*_cleaned.html"), key=lambda x: int(x.split('_')[1]))
    #print cleaned_html 
    with open(html_file, 'w') as fout:
        #cleaned_html = sorted(glob.glob(book + "*_cleaned.html"))
        for line in fileinput.input(cleaned_html):
            fout.write(line)

**Comment by lebshah** [comment]
And changes in Clean.py

    articlepublished_time = head_doc.cssselect('meta[property="article:published_time"]')[0].get('content')

    articlepublished_time_filename=dateutil.parser.parse(articlepublished_time).strftime('%Y%m%d')
    articlepublished_time_bookname=dateutil.parser.parse(articlepublished_time).strftime('%B %d, %Y')

    cleaned_file = os.path.splitext(os.path.basename(file_name))[0] +"_"+articlepublished_time_filename+ "_cleaned.html"

    for ad_by_facebook in body_doc.xpath("//iframe"):
        ad_by_facebook.getparent().remove(ad_by_facebook)
    #print articlepublished_time_bookname
    for post_navigation_assistive in body_doc.xpath("//nav[./p/@class='assistive-text']"):
        post_navigation_assistive.getparent().remove(post_navigation_assistive)

**Comment by gnijuohz** [comment]
Hey! Thanks for spending time on this! It's much appreciated.

About the changes you made:

1. I see you are sorting by creation date of the html file, however, Scrapy doesn't crawl the site in exact order, so that date may not correlate well to published date. However, it's still better than what I was doing. Thanks! 

I can probably get the published dates of each article and create a dictionary like {filename: published_date) and use it later. (use a simple database or file for that should work too) It's on my agenda but haven't really get back to it.

2.  If you look at the epub files I generated [here] (https://github.com/gnijuohz/geeksforgeeks-as-books/tree/master/goodies/geeksforgeeks/epub), it already removed the stuff you're trying to remove. [boilerpipy](https://github.com/harshavardhana/boilerpipy) is used for that. It's a library to extract only the article from a webpage.

3. I heard PyCharm is pretty good but I never used it. I mostly use GIthub's [atom](https://atom.io/).

**Comment by lebshah** [comment]
1.  
I actually used the published date of the article, if you open GEEKSFORGEEKS  site for any category, then you will find that the articles are sorted(latest article on the top) and there is DATE written there on which it was published.
I knew that the HTML file must have that somewhere, I found that in the HTML.

meta[property="article:published_time"]

I extracted this info and add that date in the file name for sorting, I also passed this date to the restructured HTML to add it in the articles in the books.  

2.
I was using your code only but somehow it was not working on windows. I only copied your code manually and am running on command prompt.I really got tired so I did not fixed that as I have to run this only a few times ha ha ha.

**Comment by lebshah** [comment]
But it would have been better if we can remove the duplicate items, there are a lot of them.

**Comment by gnijuohz** [comment]
Ah, sorry I didn't read your code more carefully. I was aware that the published data is in the html file and was only thinking along the path of storing a dictionary of articles and published date... adding that into the file name for sorting is probably a better and easier approach.

If you don't mind, you can push some code to this repo or I can add a credit to you when I update the code and readme file.

The duplicate is because I was trying to create a separate book for each category/tag.  Feel free to make other changes and get back to me!

**Comment by lebshah** [comment]
It's okay please do the changes it is your code, I just did some modifications. I am thankful to your work in the first place. Your code also works for GeeksQuiz site with slight modifications.

BTW a small change is required in generate_book.py . The previous code failed once due to "_" inside the file name itself, to avoid that I found a new method rsplit("_",2). 

This will only split the file name into parts for the first two instances of "_" from the right hand side. So there no concern for "_" in file name.

Previous Code:
cleaned_html = sorted(glob.glob(book + "*_cleaned.html"), key=lambda x: int(x.split('_')[1]))

Changed New Code:
cleaned_html = sorted(glob.glob(book + "*_cleaned.html"), key=lambda x: int(x.rsplit('_',2)[1]))

Is there a way to get that code colouring also?.

**Comment by lebshah** [comment]
![image](https://cloud.githubusercontent.com/assets/14202994/9874935/e5dc714e-5bc7-11e5-81ab-c64b429d5def.png)

**Comment by lebshah** [comment]
![image](https://cloud.githubusercontent.com/assets/14202994/9875013/5cbe0a70-5bc8-11e5-9564-791ab48ba3ea.png)

**Comment by lebshah** [comment]
![image](https://cloud.githubusercontent.com/assets/14202994/9875031/7dce1304-5bc8-11e5-8930-6873a42a2387.png)
